# Generated by Django 4.1 on 2024-06-08 02:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                ("barcode_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Fruit",
            fields=[
                ("fruit_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fruit_name", models.CharField(max_length=50)),
                ("fruit_day_plus", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Origin",
            fields=[
                ("origin_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("origin_location", models.CharField(max_length=200)),
                ("origin_address", models.CharField(max_length=200)),
                ("origin_longitude", models.CharField(max_length=200)),
                ("origin_latitude", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "warehouse_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("warehouse_name", models.CharField(max_length=100)),
                ("warehouse_longitude", models.CharField(max_length=100)),
                ("warehouse_latitude", models.CharField(max_length=100)),
                ("warehouse_address", models.CharField(max_length=200)),
                ("warehouse_capacity", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehousing",
            fields=[
                (
                    "warehousing_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "warehousing_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("warehousing_quantity", models.IntegerField(default=0)),
                (
                    "warehousing_until",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("warehousing_price", models.IntegerField(default=0)),
                (
                    "warehouse",
                    models.ForeignKey(
                        db_column="warehouse_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                ("shipping_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "shipping_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("shipping_quantity", models.IntegerField(default=0)),
                ("shipping_price", models.IntegerField(default=0)),
                (
                    "barcode",
                    models.ForeignKey(
                        db_column="barcode_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.barcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "inventory_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("inventory_quantity", models.IntegerField(default=0)),
                (
                    "inventory_expiration",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "fruit",
                    models.ForeignKey(
                        db_column="fruit_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.fruit",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        db_column="warehouse_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.warehouse",
                    ),
                ),
                (
                    "warehousing",
                    models.ForeignKey(
                        db_column="warehousing_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.warehousing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="barcode",
            name="fruit",
            field=models.ForeignKey(
                db_column="fruit_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.fruit",
            ),
        ),
        migrations.AddField(
            model_name="barcode",
            name="origin",
            field=models.ForeignKey(
                db_column="origin_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.origin",
            ),
        ),
    ]
