# Generated by Django 4.1 on 2024-06-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehousing_history",
            fields=[
                (
                    "warehousing_history_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "fruit",
                    models.ForeignKey(
                        db_column="fruit_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.fruit",
                    ),
                ),
                (
                    "warehousing",
                    models.ForeignKey(
                        db_column="warehousing_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.warehousing",
                    ),
                ),
            ],
        ),
    ]
