# Generated by Django 4.1 on 2024-06-08 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_warehousing_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehousing_history",
            name="barcode",
            field=models.ForeignKey(
                db_column="barcode_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.barcode",
            ),
            preserve_default=False,
        ),
    ]
