# Generated by Django 4.1 on 2024-06-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_warehousing_history_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehousing_history",
            name="inventory",
            field=models.ForeignKey(
                db_column="inventory_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.inventory",
            ),
            preserve_default=False,
        ),
    ]
