# Generated by Django 4.1 on 2024-06-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_inventory_user_shipping_user_warehousing_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehousing",
            name="barcode",
            field=models.ForeignKey(
                db_column="barcode_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.barcode",
            ),
            preserve_default=False,
        ),
    ]
