# Generated by Django 4.1 on 2024-06-09 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_warehousing_barcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fruit",
            old_name="fruit_day_plus",
            new_name="fruit_plus_day",
        ),
    ]
